Added entry for paper accepted as ICAART
aibasel/bib pull request #13
Opened 2024-12-10 18:07 UTC by ThatGuyIKnow

Added entry for short paper accepted at ICAART.

@inproceedings{joergensen-et-al-icaart2025,
  author =       "Oliver Joergensen and Vy Le and Tin Nguyen and Ginel Dorleon",
  title =        "Optimizing Elevator Performance with SARL Multi-Agent Systems: A Distributed Approach for Enhanced Responsiveness and Efficiency",
  booktitle =    "Proceedings of the International Conference on Agents and Artificial Intelligence (ICAART)",
  year =         "2025",
  note =         "Short Paper"
}

2024-12-10 19:44 UTC, jendrikseipp requested changes
Thanks for the PR. As usual, there are some nitpicks :)

2024-12-10 19:44 UTC, jendrikseipp commented on literatur.bib
> +  note = "Short Paper"
We usually don't mark short papers, so I suggest to remove the note.

2024-12-10 19:44 UTC, jendrikseipp commented on literatur.bib
> +  booktitle =    "Proceedings of the International Conference on Agents and Artificial Intelligence (ICAART)",
Can you please add a long entry for the conference in crossref.bib and an abbreviated one in crossref-short.bib? See the other examples as a reference. Also, the booktitle should state "Proceedings of the Xth International ..." with X substituted for the correct number, of course.

2024-12-10 19:44 UTC, jendrikseipp commented on literatur.bib
> +  title =        "Optimizing Elevator Performance with {SARL} Multi-Agent Systems: A Distributed Approach for Enhanced Responsiveness and Efficiency",
```suggestion
  title =        "Optimizing Elevator Performance with {SARL} Multi-Agent Systems: {A} Distributed Approach for Enhanced Responsiveness and Efficiency",
```

2024-12-11 07:41 UTC, ThatGuyIKnow commented
Included requested changes

2024-12-11 13:47 UTC, merged